version: '3.7'

services:
  angular-front:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/myapp
    container_name: petro-front
    restart: always
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: >
      bash -c "npm install && npm run start"

