version: '3.7'

services:
  ts-node-docker:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/myapp
      # - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    restart: always
    expose:
      - '8081'
    ports:
      - '8081:8081'
    command: >
      bash -c "npm install && npm run dev"